abonapp/urls.py
from django.urls import path, include, re_path

from abonapp import views

app_name = 'abonapp'

subscriber_patterns = [
    path('', views.AbonHomeUpdateView.as_view(), name='abon_home'),
    path('services/', views.AbonServices.as_view(), name='abon_services'),
    path('amount/', views.abonamount, name='abon_amount'),
    path('debts/', views.DebtsListView.as_view(), name='abon_debts'),
    path('pay/', views.PayHistoryListView.as_view(), name='abon_phistory'),
    path('addinvoice/', views.add_invoice, name='add_invoice'),
    path('pick/', views.pick_tariff, name='pick_tariff'),
    path('passport_view/', views.PassportUpdateView.as_view(), name='passport_view'),
    # path('reset_ip/', views.reset_ip, name='reset_ip'),
    path('unsubscribe_service/<int:abon_tariff_id>/', views.unsubscribe_service, name='unsubscribe_service'),
    path('dev/', views.dev, name='dev'),
    path('del/', views.DelAbonDeleteView.as_view(), name='del_abon'),
    path('clear_dev/', views.clear_dev, name='clear_dev'),
    path('task_log/', views.TaskLogListView.as_view(), name='task_log'),
    path('user_dev/', views.save_user_dev_port, name='save_user_dev_port'),
    path('telephones/', views.tels, name='telephones'),
    path('tel/add/', views.tel_add, name='telephone_new'),
    path('tel/del/', views.tel_del, name='telephone_del'),
    path('markers/', views.EditSibscriberMarkers.as_view(), name='markers_edit'),
    path('session/free/', views.UserSessionFree.as_view(), name='user_session_free'),
    path('periodic_pay/', views.add_edit_periodic_pay, name='add_periodic_pay'),
    path('periodic_pay/<int:periodic_pay_id>/', views.add_edit_periodic_pay, name='add_periodic_pay'),
    path('periodic_pay/<int:periodic_pay_id>/del/', views.del_periodic_pay, name='del_periodic_pay'),
    path('ping/', views.abon_ping, name='ping'),
    path('set_auto_continue_service/', views.set_auto_continue_service, name='set_auto_continue_service'),
    path('update_ip/', views.IpUpdateView.as_view(), name='update_ip')
]

group_patterns = [
    path('', views.PeoplesListView.as_view(), name='people_list'),
    path('addabon/', views.AbonCreateView.as_view(), name='add_abon'),
    path('services/', views.chgroup_tariff, name='ch_group_tariff'),
    path('phonebook/', views.phonebook, name='phonebook'),
    path('export/', views.abon_export, name='abon_export'),
    path('street/add/', views.street_add, name='street_add'),
    path('street/edit', views.street_edit, name='street_edit'),
    path('street/<int:sid>/delete/', views.street_del, name='street_del'),
    path('active_networks/', views.active_nets, name='active_nets'),
    path('attach_nas/', views.attach_nas, name='attach_nas'),
    re_path('^(?P<uname>\w{1,127})/', include(subscriber_patterns))
]

urlpatterns = [
    path('', views.GroupListView.as_view(), name='group_list'),
    path('<int:gid>/', include(group_patterns)),
    path('log/', views.LogListView.as_view(), name='log'),
    path('debtors/', views.DebtorsListView.as_view(), name='debtors'),
    path('contacts/vcards/', views.vcards, name='vcards'),

    # Api's
    path('api/abons/', views.abons),
    path('api/abon_filter/', views.search_abon),
    path('api/dhcp_lever/', views.DhcpLever.as_view())
]

devapp/urls.py
from django.urls import path, re_path
from . import views

app_name = 'devapp'

urlpatterns = [
    path('', views.GroupsListView.as_view(), name='group_list'),
    path('devices_without_groups/', views.DevicesWithoutGroupsListView.as_view(), name='devices_null_group'),
    path('fix_onu/', views.fix_onu, name='fix_onu'),
    path('<int:device_id>/reboot/', views.RebootDevice.as_view(), name='reboot'),
    path('<int:group_id>/', views.DevicesListView.as_view(), name='devs'),
    path('<int:group_id>/add/', views.DeviceCreateView.as_view(), name='add'),
    path('<int:group_id>/<int:device_id>/', views.devview, name='view'),
    path('<int:group_id>/<int:device_id>/del/', views.DeviceDeleteView.as_view(), name='del'),
    path('<int:group_id>/<int:device_id>/add/', views.add_single_port, name='add_port'),
    path('<int:group_id>/<int:device_id>/edit/', views.DeviceUpdate.as_view(), name='edit'),
    path('<int:group_id>/<int:device_id>/edit_extra/', views.DeviceUpdateExtra.as_view(), name='extra_data_edit'),
    path('<int:group_id>/<int:device_id>/ports/<int:port_id>/fix_port_conflict/', views.fix_port_conflict, name='fix_port_conflict'),
    path('<int:group_id>/<int:device_id>/ports/<int:port_id>/show_subscriber_on_port/', views.ShowSubscriberOnPort.as_view(), name='show_subscriber_on_port'),
    path('<int:group_id>/<int:device_id>/ports_add/', views.add_ports, name='add_ports'),
    path('<int:group_id>/<int:device_id>/register_device/', views.register_device, name='dev_register'),
    re_path('^(\d+)/(?P<device_id>\d+)/(?P<port_id>\d+)_(?P<status>[0-1]{1})$', views.toggle_port, name='port_toggle'),
    path('<int:group_id>/<int:device_id>/<int:port_id>/del/', views.delete_single_port, name='del_port'),
    path('<int:group_id>/<int:device_id>/<int:port_id>/edit/', views.EditSinglePort.as_view(), name='edit_port'),
    path('fix_device_group/<int:device_id>/', views.fix_device_group, name='fix_device_group'),
    path('search_dev/', views.search_dev),

    # Monitoring api
    path('on_device_event/', views.OnDeviceMonitoringEvent.as_view()),

    # Nagios mon generate
    path('nagios/hosts/', views.nagios_objects_conf, name='nagios_objects_conf'),
    path('api/getall/', views.DevicesGetListView.as_view(), name='nagios_get_all_hosts')
]

djing/urls.py
from django.urls import path, include
from django.conf import settings

from .views import home

urlpatterns = [
    path('', home),
    path('accounts/', include('accounts_app.urls', namespace='acc_app')),
    path('abons/', include('abonapp.urls', namespace='abonapp')),
    path('tarifs/', include('tariff_app.urls', namespace='tarifs')),
    path('search/', include('searchapp.urls', namespace='searchapp')),
    path('dev/', include('devapp.urls', namespace='devapp')),
    path('map/', include('mapapp.urls', namespace='mapapp')),
    path('statistic/', include('traf_stat.urls', namespace='traf_stat')),
    path('tasks/', include('taskapp.urls', namespace='taskapp')),
    path('client/', include('clientsideapp.urls', namespace='client_side')),
    path('msg/', include('msg_app.urls', namespace='msg_app')),
    path('groups/', include('group_app.urls', namespace='group_app')),
    path('ip_pool/', include('ip_pool.urls', namespace='ip_pool')),
    path('messenger/', include('messenger.urls', namespace='messenger')),
    path('gw/', include('gw_app.urls', namespace='gw_app')),
    path('new_customers/', include('new_customers.urls', namespace='new_customers')),
    path('fin/', include('finapp.urls', namespace='finapp')),
    path('docs/', include('docsapp.urls', namespace='docsapp'))

    # Switch language
    #path(r'i18n/', include('django.conf.urls.i18n')),

]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    from django.contrib import admin

    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend(staticfiles_urlpatterns())
    urlpatterns.append(path('admin/', admin.site.urls))

finapp/urls.py
from django.urls import path
from finapp import views


app_name = 'finapp'

urlpatterns = [
    path('', views.AllTimeGatewaysListView.as_view(), name='alltime_gateways_list'),

    path('fin_report/', views.BasicFinReport.as_view(), name='fin_report'),

    path('add/', views.AddAllTimeGateway.as_view(), name='add_alltime_gateway'),

    path('<slug:pay_slug>/pay_history/', views.PayHistoryListView.as_view(), name='pay_history'),

    path('<slug:pay_slug>/make_pay/', views.AllTimePay.as_view(), name='all_time_pay'),

    path('<slug:pay_slug>/edit/', views.EditPayUpdateView.as_view(), name='edit_pay_gw'),
]

abonapp/models.py
from datetime import datetime
from typing import Optional

from accounts_app.models import UserProfile, MyUserManager, BaseAccount
from bitfield import BitField
from django.conf import settings
from django.core import validators
from django.core.validators import RegexValidator
from django.db import models, transaction
from django.db.models.signals import post_init, pre_save
from django.dispatch import receiver
from django.shortcuts import resolve_url
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _, gettext
from djing.lib import LogicError
from group_app.models import Group
from gw_app.nas_managers import SubnetQueue, NasFailedResult, NasNetworkError
from tariff_app.models import Tariff, PeriodicPay


class AbonLog(models.Model):
    abon = models.ForeignKey('Abon', on_delete=models.CASCADE)
    amount = models.FloatField(default=0.0)
    author = models.ForeignKey(
        UserProfile, on_delete=models.SET_NULL,
        related_name='+', blank=True, null=True
    )
    comment = models.CharField(max_length=128)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'abonent_log'
        ordering = '-date',

    def __str__(self):
        return self.comment


class AbonTariff(models.Model):
    tariff = models.ForeignKey(
        Tariff,
        on_delete=models.CASCADE,
        related_name='linkto_tariff'
    )

    time_start = models.DateTimeField(null=True, blank=True, default=None)

    deadline = models.DateTimeField(null=True, blank=True, default=None)

    def calc_amount_service(self):
        amount = self.tariff.amount
        return round(amount, 2)

    def __str__(self):
        return "%s: %s" % (
            self.deadline,
            self.tariff.title
        )

    class Meta:
        db_table = 'abonent_tariff'
        permissions = (
            ('can_complete_service', _('finish service perm')),
        )
        verbose_name = _('Abon service')
        verbose_name_plural = _('Abon services')
        ordering = ('time_start',)


class AbonStreet(models.Model):
    name = models.CharField(_('Street title'), max_length=64)
    group = models.ForeignKey(Group, verbose_name=_('User group'), on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'abon_street'
        verbose_name = _('Street')
        verbose_name_plural = _('Streets')
        ordering = 'name',


class AbonManager(MyUserManager):
    def get_queryset(self):
        return super(AbonManager, self).get_queryset().filter(is_admin=False)

    def filter_ip_address(self, group_ids: tuple, nas_id: int):
        nas_id = int(nas_id)
        if not isinstance(group_ids, tuple):
            group_ids = tuple(group_ids)
        return self.raw(
            'SELECT baseaccount_ptr_id, ip_address FROM abonent '
            'WHERE group_id IN %s AND nas_id=%s AND ip_address IS NOT NULL '
            'ORDER BY inet_aton(ip_address) ASC',
            params=(group_ids, str(nas_id))
        )


class Abon(BaseAccount):
    current_tariff = models.OneToOneField(
        AbonTariff,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        default=None
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True, null=True,
        verbose_name=_('User group')
    )
    ballance = models.FloatField(default=0.0)
    ip_address = models.GenericIPAddressField(
        verbose_name=_('Ip address'),
        null=True,
        blank=True
    )
    description = models.TextField(
        _('Comment'),
        null=True,
        blank=True
    )
    street = models.ForeignKey(
        AbonStreet,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name=_('Street')
    )
    house = models.CharField(
        _('House'),
        max_length=12,
        null=True,
        blank=True
    )
    device = models.ForeignKey(
        'devapp.Device',
        null=True,
        blank=True,
        on_delete=models.SET_NULL
    )
    dev_port = models.ForeignKey(
        'devapp.Port',
        null=True,
        blank=True,
        on_delete=models.SET_NULL
    )
    is_dynamic_ip = models.BooleanField(
        _('Is dynamic ip'),
        default=False
    )
    nas = models.ForeignKey(
        'gw_app.NASModel',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        verbose_name=_('Network access server'),
        default=None
    )
    autoconnect_service = models.BooleanField(
        _('Automatically connect next service'),
        default=False
    )
    last_connected_tariff = models.ForeignKey(
        Tariff, verbose_name=_('Last connected service'),
        on_delete=models.SET_NULL, null=True, blank=True, default=None
    )

    MARKER_FLAGS = (
        ('icon_donkey', _('Donkey')),
        ('icon_fire', _('Fire')),
        ('icon_ok', _('Ok')),
        ('icon_king', _('King')),
        ('icon_tv', _('TV')),
        ('icon_smile', _('Smile')),
        ('icon_dollar', _('Dollar')),
        ('icon_service', _('Service')),
        ('icon_mrk', _('Marker'))
    )
    markers = BitField(flags=MARKER_FLAGS, default=0)

    def get_flag_icons(self):
        """
        Return icon list of set flags from self.markers
        :return: ['m-icon-donkey', 'm-icon-tv', ...]
        """
        return tuple("m-%s" % name for name, state in self.markers if state)

    def active_tariff(self):
        return self.current_tariff

    objects = AbonManager()

    class Meta:
        db_table = 'abonent'
        permissions = (
            ('can_buy_tariff', _('Buy service perm')),
            ('can_add_ballance', _('fill account')),
            ('can_ping', _('Can ping'))
        )
        verbose_name = _('Abon')
        verbose_name_plural = _('Abons')
        ordering = ('fio',)
        unique_together = ('ip_address', 'nas')

    def add_ballance(self, current_user, amount, comment):
        AbonLog.objects.create(
            abon=self,
            amount=amount,
            author=current_user if isinstance(current_user,
                                              UserProfile) else None,
            comment=comment
        )
        self.ballance += amount

    def pick_tariff(self, tariff, author, comment=None, deadline=None) -> None:
        """
        Trying to buy a service if enough money.
        :param tariff: instance of tariff_app.models.Tariff.
        :param author: Instance of accounts_app.models.UserProfile.
        Who connected this service. May be None if author is a system.
        :param comment: Optional text for logging this pay.
        :param deadline: Instance of datetime.datetime. Date when service is
        expired.
        :return: Nothing
        """
        if not isinstance(tariff, Tariff):
            raise TypeError

        amount = round(tariff.amount, 2)

        if tariff.is_admin and author is not None:
            if not author.is_staff:
                raise LogicError(
                    _('User that is no staff can not buy admin services')
                )

        if self.current_tariff is not None:
            if self.current_tariff.tariff == tariff:
                # if service already connected
                raise LogicError(_('That service already activated'))
            else:
                # if service is present then speak about it
                raise LogicError(_('Service already activated'))

        # if not enough money
        if self.ballance < amount:
            raise LogicError(_('%s not enough money for service %s') % (
                self.username, tariff.title
            ))

        with transaction.atomic():
            new_abtar = AbonTariff.objects.create(
                deadline=deadline, tariff=tariff
            )
            self.current_tariff = new_abtar
            if self.last_connected_tariff != tariff:
                self.last_connected_tariff = tariff

            # charge for the service
            self.ballance -= amount

            self.save(update_fields=(
                'ballance',
                'current_tariff',
                'last_connected_tariff'
            ))

            # make log about it
            AbonLog.objects.create(
                abon=self, amount=-tariff.amount,
                author=author if isinstance(author, UserProfile) else None,
                comment=comment or _('Buy service default log')
            )

    def attach_ip_addr(self, ip, strict=False):
        """
        Attach ip address to account
        :param ip: Instance of str or ip_address
        :param strict: If strict is True then ip not replaced quietly
        :return: None
        """
        if strict and self.ip_address:
            raise LogicError('Ip address already exists')
        self.ip_address = ip
        self.save(update_fields=('ip_address',))

    def free_ip_addr(self) -> bool:
        if self.ip_address:
            self.ip_address = None
            self.save(update_fields=('ip_address',))
            return True
        return False

    # is subscriber have access to service,
    # view in tariff_app.custom_tariffs.<TariffBase>.manage_access()
    def is_access(self) -> bool:
        if not self.is_active:
            return False
        abon_tariff = self.active_tariff()
        if abon_tariff is None:
            return False
        trf = abon_tariff.tariff
        ct = trf.get_calc_type()(abon_tariff)
        return ct.manage_access(self)

    # make subscriber from agent structure
    def build_agent_struct(self):
        if not self.ip_address:
            return
        abon_tariff = self.active_tariff()
        if abon_tariff:
            abon_tariff = abon_tariff.tariff
            return SubnetQueue(
                name="uid%d" % self.pk,
                network=self.ip_address,
                max_limit=(abon_tariff.speedIn, abon_tariff.speedOut),

abonapp/templates/abonapp/group_list.html
{% extends 'base.html' %}
{% load dpagination i18n %}

{% block title %}{% trans 'User groups' %}{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><span class="glyphicon glyphicon-home"></span></li>
        <li class="active">{% trans 'User groups' %}</li>
    </ol>
{% endblock %}

{% block page-header %}
    {% trans 'User groups' %}
{% endblock %}

{% block main %}
    <div class="table-responsive">
        <table class="table table-striped table-bordered">
            <thead>
            <tr>
                <th width="50">#</th>
                <th>
                    <a href="{% url 'abonapp:group_list' %}?{% url_order_by request order_by='title' %}">
                        {% trans 'Group title' %}
                    </a>
                    {% if order_by == 'title' %}<span class="glyphicon glyphicon-filter"></span>{% endif %}
                </th>
                <th width="100" class="hidden-xs">
                    {% trans 'Number of subscribers' %}
                </th>
                <th width="100">#</th>
            </tr>
            </thead>
            <tbody>
            {% for gr in groups %}
                <tr>
                    {% url 'abonapp:people_list' gr.pk as aburl %}
                    <td><a href="{{ aburl }}">{{ gr.pk }}</a></td>
                    <td><a href="{{ aburl }}">{{ gr.title }}</a></td>
                    <td class="hidden-xs">{{ gr.usercount }}</td>
                    <td class="btn-group btn-group-sm">
                        <a href="{% url 'abonapp:ch_group_tariff' gr.pk %}" class="btn btn-default" title="{% trans 'User groups' %}">
                            <span class="glyphicon glyphicon-cog"></span>
                        </a>
                        <a href="{% url 'abonapp:attach_nas' gr.pk %}" class="btn btn-default btn-modal" title="{% trans 'NAS' %}">
                            <span class="glyphicon glyphicon-globe"></span>
                        </a>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="4"><a href="#">{% trans 'Groups was not found' %}</a></td>
                </tr>
            {% endfor %}
            </tbody>
            <tfoot>
            <tr>
                <td colspan="4" class="btn-group btn-group-sm">
                    {% if perms.abonapp.view_abonlog %}
                        <a href="{% url 'abonapp:log' %}" class="btn btn-default">
                            <span class="glyphicon glyphicon-record"></span> <span class="hidden-xs">{% trans 'Subscribers actions' %}</span>
                        </a>
                    {% endif %}
                    {% if perms.abonapp.view_invoiceforpayment %}
                        <a href="{% url 'abonapp:debtors' %}" class="btn btn-default">
                            <span class="glyphicon glyphicon-exclamation-sign"></span> <span class="hidden-xs">{% trans 'List of debtors' %}</span>
                        </a>
                    {% endif %}
                    <a href="{% url 'abonapp:vcards' %}" class="btn btn-default">
                        <span class="glyphicon glyphicon-phone"></span>
                        <span class="hidden-xs">{% trans 'Export vCards' %}</span>
                    </a>
                </td>
            </tr>
            </tfoot>
        </table>
    </div>
{% endblock %}

abonapp/templates/abonapp/service.html
{% extends request.is_ajax|yesno:'nullcont.htm,abonapp/ext.htm' %}
{% load i18n %}
{% block content %}

    <div class="row">
        <div class="col-sm-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">{% trans 'Services for buy' %}</h3>
                </div>
                <div class="panel-body">
                    <table class="table table-condensed">
                        <thead>
                        <tr>
                            <th>{% trans 'Pick a service' %}</th>
                            <th>{% trans 'Service' %}</th>
                            <th>{% trans 'Price' %}</th>
                            <th>{% trans 'Speed In' %}</th>
                            <th>{% trans 'Speed Out' %}</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% with can_ch_trf=perms.tariff_app.change_tariff %}
                        {% for service in services %}
                        <tr>
                            <td>
                                {% if abon_tariff %}
                                    <a href="#" class="btn btn-sm btn-default disabled">
                                        <span class="glyphicon glyphicon-shopping-cart"></span>
                                    </a>
                                {% else %}
                                    <a href="{% url 'abonapp:pick_tariff' group.pk abon.username %}?selected_tariff={{ service.pk }}"
                                       class="btn btn-sm btn-default" title="{{ service.get_calc_type_display }}" data-toggle="tooltip">
                                        <span class="glyphicon glyphicon-shopping-cart"></span>
                                    </a>
                                {% endif %}
                            </td>
                            <td>
                                {% if can_ch_trf %}
                                    <a href="{% url 'tarifs:edit' service.pk %}" title="{{ service.descr }}" data-toggle="tooltip"><b>{{ service.title }}</b></a>
                                {% else %}
                                    {{ service.title }}
                                {% endif %}
                            </td>
                            <td>{{ service.amount }} {% trans 'currency' %}</td>
                            <td>{{ service.speedIn }}</td>
                            <td>{{ service.speedOut }}</td>
                        </tr>
                        {% empty %}
                        <tr><td colspan="5">
                            {% trans 'This group has no services' %}
                            <a href="{% url 'abonapp:ch_group_tariff' group.pk %}" class="btn btn-sm btn-default" title="{% trans 'User groups' %}">
                                <span class="glyphicon glyphicon-cog"></span> {% trans 'Tariffs in groups' %}
                            </a>
                        </td></tr>
                        {% endfor %}
                        {% endwith %}
                        </tbody>
                    </table>
                    <a href="{% url 'abonapp:ch_group_tariff' group.pk %}" class="btn btn-sm btn-primary" title="{% trans 'User groups' %}">
                        <span class="glyphicon glyphicon-cog"></span> {% trans 'Attach services to group' %}
                    </a>
                </div>
            </div>
        </div>
        <div class="col-sm-6">

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">{% trans "Subscriber's service" %}</h3>
                </div>
                <div class="panel-body">
                    <dl class="dl-horizontal">
                        {% if abon_tariff %}
                            <dt>{% trans 'Service' %}</dt>
                            <dd>
                                {% if abon_tariff.tariff %}
                                    {% if perms.tariff_app.change_tariff %}
                                        <a href="{% url 'tarifs:edit' abon_tariff.tariff.pk %}" title="{{ abon_tariff.time_start|default:'' }}">
                                            {{ abon_tariff.tariff.title }}
                                        </a>
                                    {% else %}
                                        {{ abon_tariff.tariff.title }}
                                    {% endif %}
                                {% else %}
                                    <b class="text-danger">{% trans 'We have a problem in DB: AbonTariff instance has no related to service' %}</b>
                                {% endif %}
                            </dd>
                            <dt>{% trans 'Sum' %}</dt>
                            <dd>{{ abon_tariff.tariff.amount }} {% trans 'currency' %}.</dd>

                            <dt>{% trans 'Input speed' %}</dt>
                            <dd>{{ abon_tariff.tariff.speedIn }}</dd>

                            <dt>{% trans 'Output speed' %}</dt>
                            <dd>{{ abon_tariff.tariff.speedOut }}</dd>

                            <dt>{% trans 'Date of start' %}</dt>
                            <dd>{{ abon_tariff.time_start|date:"d E Y, l H:i" }}</dd>

                            <dt>{% trans 'Works until' %}</dt>
                            <dd>{{ abon_tariff.deadline|date:"d E Y, l H:i" }}</dd>
                        {% else %}
                            <dt>{% trans 'Subscriber has no service' %}</dt>
                            <dd>
                                <a href="{% url 'abonapp:pick_tariff' group.pk abon.username %}">
                                    {% trans 'Buy service' %}
                                </a>
                            </dd>
                        {% endif %}

                        {% if abon.last_connected_tariff %}
                            <dt>{% trans 'Last connected service' %}</dt>
                            <dd><a href="{{ abon.last_connected_tariff.get_absolute_url }}">{{ abon.last_connected_tariff.title }}</a></dd>
                        {% endif %}

                        <dt>{% trans 'Auto continue service.' %}</dt>
                        <dd>
                            <input type="checkbox" data-url="{% url 'abonapp:set_auto_continue_service' group.pk abon.username %}" class="autosave" {{ abon.autoconnect_service|yesno:'checked,' }}>
                            <a href="https://github.com/nerosketch/djing/blob/devel/docs/tarifs.md" title="{% trans 'Help' %}" data-toggle="tooltip">?</a>
                        </dd>
                    </dl>

                    {% if abon_tariff.tariff.descr %}
                        <p>{{ abon_tariff.tariff.descr }}</p>
                    {% endif %}

                    {% if abon_tariff %}
                        {% if perms.abonapp.can_complete_service %}
                            <a href="{% url 'abonapp:unsubscribe_service' group.pk abon.username abon_tariff.pk %}" class="btn btn-sm btn-danger">
                                <span class="glyphicon glyphicon-remove-circle"></span> {% trans 'Finish service' %}
                            </a>
                        {% else %}
                            <a href="#" class="btn btn-sm btn-danger disabled">
                                <span class="glyphicon glyphicon-remove-circle"></span> {% trans 'Finish service' %}
                            </a>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>

        {% if perms.tariff_app.view_periodic_pay %}
        <div class="col-sm-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">{% trans 'Periodic pay' %}</h3>
                </div>
                <div class="panel-body">
                    {% if periodic_pay %}
                        <dl class="dl-horizontal">
                            <dt>{% trans 'Pay logic' %}</dt>
                            <dd>{{ periodic_pay.periodic_pay }}</dd>
                            <dt>{% trans 'Last pay' %}</dt>
                            <dd>{{ periodic_pay.last_pay|default:'Not yet paid' }}</dd>
                            <dt>{% trans 'Next time to pay' %}</dt>
                            <dd>{{ periodic_pay.next_pay|date:'d E Y' }}</dd>
                        </dl>
                        <a href="{% url 'abonapp:del_periodic_pay' group.pk abon.username periodic_pay.pk %}" class="btn btn-sm btn-danger">
                            <span class="glyphicon glyphicon-remove-circle"></span> {% trans 'Remove periodic pay' %}
                        </a>
                    {% else %}
                        <a href="{% url 'abonapp:add_periodic_pay' group.pk abon.username %}" class="btn btn-primary btn-sm btn-modal">
                            <span class="glyphicon glyphicon-plus"></span> {% trans 'Add periodic pay' %}
                        </a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endif %}

    </div>

{% endblock %}