djing/urls.py
from django.urls import path, include
from django.conf import settings

from .views import home

urlpatterns = [
    path('', home),
    path('accounts/', include('accounts_app.urls', namespace='acc_app')),
    path('abons/', include('abonapp.urls', namespace='abonapp')),
    path('tarifs/', include('tariff_app.urls', namespace='tarifs')),
    path('search/', include('searchapp.urls', namespace='searchapp')),
    path('dev/', include('devapp.urls', namespace='devapp')),
    path('map/', include('mapapp.urls', namespace='mapapp')),
    path('statistic/', include('traf_stat.urls', namespace='traf_stat')),
    path('tasks/', include('taskapp.urls', namespace='taskapp')),
    path('client/', include('clientsideapp.urls', namespace='client_side')),
    path('msg/', include('msg_app.urls', namespace='msg_app')),
    path('groups/', include('group_app.urls', namespace='group_app')),
    path('ip_pool/', include('ip_pool.urls', namespace='ip_pool')),
    path('messenger/', include('messenger.urls', namespace='messenger')),
    path('gw/', include('gw_app.urls', namespace='gw_app')),
    path('new_customers/', include('new_customers.urls', namespace='new_customers')),
    path('fin/', include('finapp.urls', namespace='finapp')),
    path('docs/', include('docsapp.urls', namespace='docsapp'))

    # Switch language
    #path(r'i18n/', include('django.conf.urls.i18n')),

]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    from django.contrib import admin

    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend(staticfiles_urlpatterns())
    urlpatterns.append(path('admin/', admin.site.urls))

docsapp/urls.py
from django.urls import path
from docsapp import views

app_name = 'docsapp'


urlpatterns = [
    path('', views.DocumentsListView.as_view(), name='docs_list'),
    path('add/', views.DocumentCreateView.as_view(), name='doc_add'),
    path('<int:pk>/', views.DocumentUpdateView.as_view(), name='doc_edit'),
    path('<int:pk>/del/', views.DocumentDeleteView.as_view(), name='doc_del'),
    path('<int:pk>/<slug:uname>/render/', views.RenderDocument.as_view(), name='doc_render'),
    path('<slug:account_name>/simple_list/', views.SimpleListView.as_view(), name='simple_list'),
]

docsapp/models.py
from django.shortcuts import resolve_url
from django.utils.translation import gettext_lazy as _
from django.core.validators import FileExtensionValidator
from django.db import models

from abonapp.models import Abon


class DocumentTemplateModel(models.Model):
    title = models.CharField(_('Title'), max_length=80, unique=True)
    doc_template = models.FileField(
        _('File docx template'), upload_to='word_docs',
        validators=[FileExtensionValidator(allowed_extensions=('docx',))]
    )

    def get_absolute_url(self):
        return resolve_url('docsapp:doc_edit', pk=self.pk)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'documents'
        ordering = ('title',)

docsapp/forms.py
from django import forms
from docsapp.models import DocumentTemplateModel


class DocumentTemplateModelForm(forms.ModelForm):
    class Meta:
        model = DocumentTemplateModel
        fields = '__all__'

docsapp/views.py
from io import BytesIO

from django.contrib import messages
from django.utils.datetime_safe import datetime
from django.utils.translation import gettext_lazy as _
from django.views.generic import UpdateView, DeleteView, CreateView, DetailView, ListView
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.exceptions import ValidationError
from django.http import HttpResponse
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from docxtpl import DocxTemplate
from docx.opc.constants import CONTENT_TYPE
from jinja2.exceptions import UndefinedError, TemplateSyntaxError

from abonapp.models import Abon
from djing.global_base_views import OrderedFilteredList
from djing.lib.mixins import LoginAdminMixin, LoginAdminPermissionMixin
from docsapp.models import DocumentTemplateModel
from docsapp.forms import DocumentTemplateModelForm


class DocumentsListView(LoginAdminMixin, OrderedFilteredList):
    model = DocumentTemplateModel


class SimpleListView(LoginAdminMixin, ListView):
    template_name = 'docsapp/simple_list.html'
    model = DocumentTemplateModel

    def get_context_data(self, **kwargs):
        kwargs.update({
            'account_name': self.kwargs.get('account_name')
        })
        return super().get_context_data(**kwargs)


class DocumentUpdateView(LoginAdminPermissionMixin, UpdateView):
    permission_required = 'docsapp.change_documenttemplatemodel'
    model = DocumentTemplateModel
    form_class = DocumentTemplateModelForm


class DocumentDeleteView(LoginAdminPermissionMixin, DeleteView):
    permission_required = 'docsapp.delete_documenttemplatemodel'
    model = DocumentTemplateModel
    success_url = reverse_lazy('docsapp:docs_list')


class DocumentCreateView(LoginAdminMixin, PermissionRequiredMixin, CreateView):
    model = DocumentTemplateModel
    form_class = DocumentTemplateModelForm
    permission_required = 'docsapp.add_documenttemplatemodel'


class RenderDocument(LoginAdminPermissionMixin, DetailView):
    model = DocumentTemplateModel
    permission_required = 'docsapp.view_documenttemplatemodel'
    context_object_name = 'document'
    extra_context = {
        'date': datetime.now()
    }

    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        self.object = obj
        acc = get_object_or_404(Abon, username=self.kwargs.get('uname'))

        try:
            doc = DocxTemplate(
                obj.doc_template.path
            )
            context = self.get_context_data(object=obj)
            context.update(self.get_context_account(acc))
            doc.render(context)

            destination_document_file = BytesIO()
            doc.get_docx().save(destination_document_file)
            resp = HttpResponse(
                destination_document_file.getvalue(),
                content_type=CONTENT_TYPE.WML_DOCUMENT
            )
            resp['Content-Disposition'] = 'attachment; filename="document.docx"'
            return resp
        except (UndefinedError, ValidationError, TemplateSyntaxError) as e:
            messages.error(request, str(e))
        return redirect('docsapp:docs_list')

    def get_context_account(self, account):
        if not isinstance(account, Abon):
            raise ValidationError(message=_('Account required and must be Abon'))
        bp = '_' * 20
        return {
            'account': account,
            'passport': getattr(account, 'passportinfo', {
                'series': bp,
                'number': bp,
                'distributor': bp,
                'date_of_acceptance': bp
            })
        }

docsapp/templates/docsapp/documenttemplatemodel_confirm_delete.html
{% extends 'base_delete_modal.html' %}
{% load i18n %}

{% block modal_form_url %}
    {% url 'docsapp:doc_del' object.pk %}
{% endblock %}

{% block modal_form_title %}
    {% trans 'Remove document' %}
{% endblock %}

{% block modal_form_text %}
    <h4>{% trans 'Are you sure you want to delete this document?' %}</h4>
{% endblock %}

docsapp/templates/docsapp/documenttemplatemodel_form.html
{% extends request.is_ajax|yesno:'bajax.html,base.html' %}
{% load i18n bootstrap3 %}

{% block main %}

    {% if object %}
        {% url 'docsapp:doc_edit' object.pk as objurl %}
    {% else %}
        {% url 'docsapp:doc_add' as objurl %}
    {% endif %}

    <form action="{{ objurl }}" method="post" enctype="multipart/form-data">{% csrf_token %}
    <div class="modal-header primary">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">
            <span class="glyphicon glyphicon-exclamation-sign"></span>

            {% if object %}
                {% trans 'Change document' %}
            {% else %}
                {% trans 'Add document' %}
            {% endif %}

        </h4>
    </div>
    <div class="modal-body">
        {% bootstrap_form form %}

        <div class="btn-group btn-group-sm">
            {% bootstrap_button _('Save') button_type="submit" button_class="btn-primary" icon="save" %}

            {% if not request.is_ajax %}
                {% url 'docsapp:docs_list' as backurl %}
                {% bootstrap_button _('Back') button_type="link" href=backurl icon="fast-backward" %}
            {% endif %}
        </div>
    </div>
</form>
{% endblock %}

docsapp/templates/docsapp/documenttemplatemodel_list.html
{% extends request.is_ajax|yesno:'bajax.html,base.html' %}
{% load i18n %}

{% block title %}
    {% trans 'Documents' %}
{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><span class="glyphicon glyphicon-home"></span></li>
        <li class="active">{% trans 'Documents' %}</li>
    </ol>
{% endblock %}

{% block page-header %}
    {% trans 'Documents' %}
{% endblock %}

{% block main %}
    <div class="table-responsive">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>.</th>
                <th class="col-md-2">{% trans 'Title' %}</th>
                <th class="col-md-4">{% trans 'File' %}</th>
                <th class="col-md-3">{% trans 'Document type' %}</th>
                <th>#</th>
            </tr>
            </thead>

            <tbody>
            {% with can_del_doc=perms.docsapp.delete_documenttemplatemodel can_ch_doc=perms.docsapp.change_documenttemplatemodel %}
            {% for doc in object_list %}
                <tr>
                    <td>{{ doc.id }}</td>
                    <td>{{ doc.title }}</td>
                    <td>{{ doc.doc_template }}</td>
                    <td>DocX</td>

                    <td class="btn-group btn-group-xs btn-group-justified">
                        {% if can_del_doc %}
                            <a href="{% url 'docsapp:doc_del' doc.pk %}" class="btn btn-danger btn-modal">
                                <span class="glyphicon glyphicon-remove"></span>
                            </a>
                        {% endif %}
                        {% if can_ch_doc %}
                            <a href="{% url 'docsapp:doc_edit' doc.id %}" class="btn btn-default btn-modal">
                                <span class="glyphicon glyphicon-edit"></span>
                            </a>
                        {% endif %}
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="6">
                        {% trans 'Documents not found' %}.
                        <a href="{% url 'docsapp:doc_add' %}" class="btn-modal">{% trans 'Add document' %}</a>
                    </td>
                </tr>
            {% endfor %}
            {% endwith %}
            </tbody>

            <tfoot>
            <tr>
                <td colspan="6">
                    <a href="{% url 'docsapp:doc_add' %}" class="btn btn-success btn-sm btn-modal">
                        <span class="glyphicon glyphicon-plus"></span> {% trans 'Add document' %}
                    </a>
                </td>
            </tr>
            </tfoot>

        </table>
    </div>
{% endblock %}

docsapp/templates/docsapp/simple_list.html
{% load i18n %}

<div class="modal-header primary">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title">{% trans 'Documents' %}</h4>
</div>
<div class="modal-body">

    <div class="panel panel-default">
        <div class="panel-body">
            <ul class="list-group">
                {% for obj in object_list %}
                    <li class="list-group-item">
                        <b>{{ obj.title }}</b>
                        <a href="{% url 'docsapp:doc_render' obj.pk account_name %}" class="btn btn-default">
                            <span class="glyphicon glyphicon-print"></span> {% trans 'Render document' %}
                        </a>
                    </li>
                {% empty %}
                    {% trans 'Documents not found' %}
                {% endfor %}
            </ul>
        </div>
    </div>

</div>