djing/urls.py
from django.urls import path, include
from django.conf import settings

from .views import home

urlpatterns = [
    path('', home),
    path('accounts/', include('accounts_app.urls', namespace='acc_app')),
    path('abons/', include('abonapp.urls', namespace='abonapp')),
    path('tarifs/', include('tariff_app.urls', namespace='tarifs')),
    path('search/', include('searchapp.urls', namespace='searchapp')),
    path('dev/', include('devapp.urls', namespace='devapp')),
    path('map/', include('mapapp.urls', namespace='mapapp')),
    path('statistic/', include('traf_stat.urls', namespace='traf_stat')),
    path('tasks/', include('taskapp.urls', namespace='taskapp')),
    path('client/', include('clientsideapp.urls', namespace='client_side')),
    path('msg/', include('msg_app.urls', namespace='msg_app')),
    path('groups/', include('group_app.urls', namespace='group_app')),
    path('ip_pool/', include('ip_pool.urls', namespace='ip_pool')),
    path('messenger/', include('messenger.urls', namespace='messenger')),
    path('gw/', include('gw_app.urls', namespace='gw_app')),
    path('new_customers/', include('new_customers.urls', namespace='new_customers')),
    path('fin/', include('finapp.urls', namespace='finapp')),
    path('docs/', include('docsapp.urls', namespace='docsapp'))

    # Switch language
    #path(r'i18n/', include('django.conf.urls.i18n')),

]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    from django.contrib import admin

    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend(staticfiles_urlpatterns())
    urlpatterns.append(path('admin/', admin.site.urls))

finapp/urls.py
from django.urls import path
from finapp import views


app_name = 'finapp'

urlpatterns = [
    path('', views.AllTimeGatewaysListView.as_view(), name='alltime_gateways_list'),

    path('fin_report/', views.BasicFinReport.as_view(), name='fin_report'),

    path('add/', views.AddAllTimeGateway.as_view(), name='add_alltime_gateway'),

    path('<slug:pay_slug>/pay_history/', views.PayHistoryListView.as_view(), name='pay_history'),

    path('<slug:pay_slug>/make_pay/', views.AllTimePay.as_view(), name='all_time_pay'),

    path('<slug:pay_slug>/edit/', views.EditPayUpdateView.as_view(), name='edit_pay_gw'),
]

finapp/models.py
from datetime import datetime
from django.db import models, connection
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from encrypted_model_fields.fields import EncryptedCharField

from abonapp.models import Abon


class AllTimePayLogManager(models.Manager):
    @staticmethod
    def by_days():
        cur = connection.cursor()
        cur.execute(
            'SELECT SUM(summ) AS alsum, '
            'DATE_FORMAT(date_add, "%Y-%m-%d") AS pay_date '
            'FROM  all_time_pay_log '
            'GROUP BY DATE_FORMAT(date_add, "%Y-%m-%d")'
        )
        while True:
            r = cur.fetchone()
            if r is None:
                break
            summ, dat = r
            yield {
                'summ': summ,
                'pay_date': datetime.strptime(dat, '%Y-%m-%d')
            }


class PayAllTimeGateway(models.Model):
    title = models.CharField(_('Title'), max_length=64)
    secret = EncryptedCharField(verbose_name=_('Secret'), max_length=64)
    service_id = models.CharField(_('Service id'), max_length=64)
    slug = models.SlugField(_('Slug'), max_length=32,
                            unique=True, allow_unicode=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('finapp:edit_pay_gw', self.slug)

    class Meta:
        db_table = 'pay_all_time_gateways'
        verbose_name = _('All time gateway')
        ordering = 'title',


# Log for pay system "AllTime"
class AllTimePayLog(models.Model):
    abon = models.ForeignKey(
        Abon,
        on_delete=models.SET_DEFAULT,
        blank=True,
        null=True,
        default=None
    )
    pay_id = models.CharField(
        max_length=36,
        unique=True,
        primary_key=True
    )
    date_add = models.DateTimeField(auto_now_add=True)
    summ = models.FloatField(_('Cost'), default=0.0)
    trade_point = models.CharField(
        _('Trade point'),
        max_length=20,
        default=None,
        null=True,
        blank=True
    )
    receipt_num = models.BigIntegerField(_('Receipt number'), default=0)
    pay_gw = models.ForeignKey(PayAllTimeGateway,
                               verbose_name=_('Pay gateway'),
                               on_delete=models.CASCADE)

    objects = AllTimePayLogManager()

    def __str__(self):
        return self.pay_id

    class Meta:
        db_table = 'all_time_pay_log'
        ordering = ('-date_add',)

finapp/forms.py
from django import forms
from finapp.models import PayAllTimeGateway


class PayAllTimeGatewayForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        instance = getattr(self, 'instance')
        if instance and instance.pk:
            self.fields['slug'].disabled = True

    def clean_slug(self):
        if self.instance and self.instance.pk:
            return self.instance.slug
        return self.data['slug']

    class Meta:
        model = PayAllTimeGateway
        fields = '__all__'

finapp/views.py
import csv
from hashlib import md5

from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db import DatabaseError, transaction
from django.db.models import Count
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, resolve_url
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.utils.translation import ugettext_lazy as _
from xmlview.decorators import xml_view
from djing import lib
from djing.global_base_views import OrderedFilteredList
from djing.lib.mixins import LoginAdminMixin, LoginAdminPermissionMixin
from finapp.forms import PayAllTimeGatewayForm
from finapp.models import AllTimePayLog, PayAllTimeGateway
from abonapp.models import Abon


class AllTimePay(DetailView):
    http_method_names = 'get',
    model = PayAllTimeGateway
    pk_url_kwarg = 'slug'
    slug_url_kwarg = 'pay_slug'

    @staticmethod
    def _bad_ret(err_id, err_description=None):
        now = timezone.now()
        r = {
            'status_code': lib.safe_int(err_id),
            'time_stamp': now.strftime("%d.%m.%Y %H:%M")
        }
        if err_description:
            r.update({'description': err_description})
        return r

    def check_sign(self, data: dict, sign: str) -> bool:
        act = lib.safe_int(data.get('ACT'))
        pay_account = data.get('PAY_ACCOUNT')
        serv_id = data.get('SERVICE_ID')
        pay_id = data.get('PAY_ID')
        md = md5()
        s = '_'.join(
            (str(act), pay_account or '', serv_id or '',
             pay_id or '', self.object.secret)
        )
        md.update(bytes(s, 'utf-8'))
        our_sign = md.hexdigest()
        return our_sign == sign

    @method_decorator(xml_view(root_node='pay-response'))
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        act = lib.safe_int(request.GET.get('ACT'))
        self.current_date = timezone.now().strftime("%d.%m.%Y %H:%M")

        if act <= 0:
            return self._bad_ret(-101, 'ACT must be more than 0')
        sign = request.GET.get('SIGN')
        if not sign:
            return self._bad_ret(-101, 'SIGN not passed')
        if not self.check_sign(request.GET, sign.lower()):
            return self._bad_ret(-101, 'Bad sign')

        try:
            if act == 1:
                return self._fetch_user_info(request.GET)
            elif act == 4:
                return self._make_pay(request.GET)
            elif act == 7:
                return self._check_pay(request.GET)
            else:
                return self._bad_ret(-101, 'ACT is not passed')
        except Abon.DoesNotExist:
            return self._bad_ret(-40, 'Account does not exist')
        except DatabaseError:
            return self._bad_ret(-90)
        except AllTimePayLog.DoesNotExist:
            return self._bad_ret(-10)
        except AttributeError:
            return self._bad_ret(-101)

    def _fetch_user_info(self, data: dict):
        pay_account = data.get('PAY_ACCOUNT')
        abon = Abon.objects.get(username=pay_account)
        fio = abon.fio
        ballance = float(abon.ballance)
        return {
            'balance': round(ballance, 2),
            'name': fio,
            'account': pay_account,
            'service_id': self.object.service_id,
            'min_amount': 10.0,
            'max_amount': 5000,
            'status_code': 21,
            'time_stamp': self.current_date
        }

    def _make_pay(self, data: dict):
        trade_point = lib.safe_int(data.get('TRADE_POINT'))
        receipt_num = lib.safe_int(data.get('RECEIPT_NUM'))
        pay_account = data.get('PAY_ACCOUNT')
        pay_id = data.get('PAY_ID')
        pay_amount = lib.safe_float(data.get('PAY_AMOUNT'))
        abon = Abon.objects.get(username=pay_account)
        pays = AllTimePayLog.objects.filter(pay_id=pay_id)
        if pays.exists():
            return self._bad_ret(-100, 'Pay already exists')

        with transaction.atomic():
            abon.add_ballance(
                None, pay_amount,
                comment='%s %.2f' % (self.object.title, pay_amount)
            )
            abon.save(update_fields=('ballance',))

            AllTimePayLog.objects.create(
                pay_id=pay_id,
                summ=pay_amount,
                abon=abon,
                trade_point=trade_point,
                receipt_num=receipt_num,
                pay_gw=self.object
            )
        return {
            'pay_id': pay_id,
            'service_id': data.get('SERVICE_ID'),
            'amount': round(pay_amount, 2),
            'status_code': 22,
            'time_stamp': self.current_date
        }

    def _check_pay(self, data: dict):
        pay_id = data.get('PAY_ID')
        pay = AllTimePayLog.objects.get(pay_id=pay_id)
        return {
            'status_code': 11,
            'time_stamp': self.current_date,
            'transaction': {
                'pay_id': pay_id,
                'service_id': data.get('SERVICE_ID'),
                'amount': round(pay.summ, 2),
                'status': 111,
                'time_stamp': pay.date_add.strftime("%d.%m.%Y %H:%M")
            }
        }


class BasicFinReport(LoginAdminMixin, ListView):
    model = AllTimePayLog
    queryset = AllTimePayLog.objects.by_days()
    template_name = 'finapp/fin_report.html'
    context_object_name = 'logs'

    def get(self, request, *args, **kwargs):
        res_format = request.GET.get('f')
        if res_format == 'csv':
            response = HttpResponse(content_type='text/csv')
            response['Content-Disposition'] = 'attachment; filename="report.csv"'
            writer = csv.writer(response, quoting=csv.QUOTE_NONNUMERIC)
            for row in self.object_list:
                writer.writerow(
                    (row['summ'], row['pay_date'].strftime('%Y-%m-%d'))
                )
            return response
        return super().get(request, *args, **kwargs)


class PayHistoryListView(LoginAdminMixin, PermissionRequiredMixin,
                         OrderedFilteredList):
    permission_required = 'group_app.view_group'
    context_object_name = 'pay_history'
    template_name = 'finapp/payHistory.html'
    model = AllTimePayLog

    def get_queryset(self):
        pay_history = AllTimePayLog.objects.filter(
            pay_gw__slug=self.kwargs.get('pay_slug')
        ).select_related('abon__group').order_by('-date_add')
        return pay_history

    def get_context_data(self, **kwargs):
        context = {
            'pay_gw': get_object_or_404(PayAllTimeGateway, slug=self.kwargs.get('pay_slug'))
        }
        context.update(kwargs)
        return super(PayHistoryListView, self).get_context_data(**context)


class AddAllTimeGateway(LoginAdminMixin, PermissionRequiredMixin, CreateView):
    permission_required = 'finapp.add_payalltimegateway'
    model = PayAllTimeGateway
    form_class = PayAllTimeGatewayForm
    success_url = reverse_lazy('finapp:alltime_gateways_list')

    def form_valid(self, form):
        messages.success(self.request, _('New pay gateway created successfully'))
        return super(AddAllTimeGateway, self).form_valid(form)


class AllTimeGatewaysListView(LoginAdminPermissionMixin, ListView):
    permission_required = 'finapp.view_payalltimegateway'
    model = PayAllTimeGateway
    queryset = PayAllTimeGateway.objects.annotate(
        pays_count=Count('alltimepaylog')
    )


class EditPayUpdateView(LoginAdminPermissionMixin, UpdateView):
    permission_required = 'finapp.change_payalltimegateway'
    model = PayAllTimeGateway
    form_class = PayAllTimeGatewayForm
    pk_url_kwarg = 'slug'
    slug_url_kwarg = 'pay_slug'

    def get_success_url(self):
        return resolve_url('finapp:edit_pay_gw', self.object.slug)

    def form_valid(self, form):
        messages.success(self.request, _('Payment gateway successfully updated'))
        return super(EditPayUpdateView, self).form_valid(form)

finapp/templates/finapp/ext.htm
{% extends request.is_ajax|yesno:'bajax.html,base.html' %}
{% load i18n %}

{% block breadcrumb %}{% endblock %}

{% block page-header %}
    <small>{% trans 'Payment gateways' %}</small>
{% endblock %}

{% block main %}
    <ul class="nav nav-tabs nav-justified">

        <li class="active">
            <a href="#">{% trans 'Payment gateways' %}</a>
        </li>

    </ul>

    <div class="tab-content">
        <div class="tab-pane active">
            {% block content %}{% endblock %}
        </div>
    </div>
{% endblock %}

finapp/templates/finapp/fin_report.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans 'Money by days' %}{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><span class="glyphicon glyphicon-home"></span></li>
        <li class="active">{% trans 'Fin report' %}</li>
    </ol>
{% endblock %}

{% block page-header %}
    {% trans 'Money by days' %}
{% endblock %}

{% block main %}
    <div class="table-responsive">
        <table class="table table-striped table-bordered">
            <thead>
            <tr>
                <th>{% trans 'Cost' %}</th>
                <th>{% trans 'Date' %}</th>
            </tr>
            </thead>
            <tbody>
            {% for l in logs %}
                <tr>
                    <td>{{ l.summ }}</td>
                    <td>{{ l.pay_date|date:"d E Y" }}</td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="2">{% trans 'Pays not found' %}</td>
                </tr>
            {% endfor %}
            </tbody>

            <thead>
            <tr>
                <td colspan="2">
                    <a href="{% url 'finapp:fin_report' %}?f=csv" target="_blank" class="btn btn-sm btn-default">
                        <span class="glyphicon glyphicon-download"></span> <span class="hidden-xs">{% trans 'Export to csv' %}</span>
                    </a>
                </td>
            </tr>
            </thead>

        </table>
    </div>
{% endblock %}

finapp/templates/finapp/payHistory.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{{ pay_gw.title }}{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><span class="glyphicon glyphicon-home"></span></li>
        <li><a href="{% url 'finapp:alltime_gateways_list' %}">{% trans 'Payment system' %}</a></li>
        <li class="active">{% trans 'Payment history' %}</li>
    </ol>
{% endblock %}

{% block page-header %}{{ pay_gw.title }}{% endblock %}


{% block main %}

    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th>{% trans 'User' %}</th>
            <th>{% trans 'Pay id' %}</th>
            <th>{% trans 'Date' %}</th>
            <th>{% trans 'Cost' %}</th>
            <th>{% trans 'Trade point' %}</th>
            <th>{% trans 'Receipt num' %}</th>
        </tr>
        </thead>
        <tbody>
        {% for pay in object_list %}
            <tr>
                <td>
                    {% if pay.abon %}
                        <a href="{{ pay.abon.get_absolute_url }}">{{ pay.abon }}</a>
                    {% else %}
                        {% trans 'Deleted' %}
                    {% endif %}
                </td>
                <td>{{ pay.pay_id }}</td>
                <td>{{ pay.date_add|date:'D d E Y H:i:s' }}</td>
                <td>{{ pay.summ }}</td>
                <td>{{ pay.trade_point|default_if_none:'&mdash;' }}</td>
                <td>{{ pay.receipt_num }}</td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="6">{% trans 'Payment history is empty' %}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

finapp/templates/finapp/payalltimegateway_form.html
{% extends request.is_ajax|yesno:'bajax.html,base.html' %}
{% load i18n bootstrap3 %}

{% block title %}
    {% if object %}
        {% trans 'Change payment gateway' %}
    {% else %}
        {% trans 'Add payment gateway' %}
    {% endif %}
{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><span class="glyphicon glyphicon-home"></span></li>
        <li><a href="{% url 'finapp:alltime_gateways_list' %}">{% trans 'Payment system' %}</a></li>
        <li class="active">
            {% if object %}
                {% trans 'Change payment gateway' %}
            {% else %}
                {% trans 'Add payment gateway' %}
            {% endif %}
        </li>
    </ol>
{% endblock %}


{% block page-header %}
    {% if object %}
        {% trans 'Change payment gateway' %}
    {% else %}
        {% trans 'Add payment gateway' %}
    {% endif %}
{% endblock %}


{% block main %}
    {% if object %}
        {% url 'finapp:edit_pay_gw' object.slug as form_url %}
    {% else %}
        {% url 'finapp:add_alltime_gateway' as form_url %}
    {% endif %}

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">{% trans 'Type info about payment gateway' %}</h3>
        </div>
        <div class="panel-body">
            <form role="form" action="{{ form_url }}" method="post">{% csrf_token %}
                <div class="form-group">
                    {% bootstrap_form form %}
                </div>
                <div class="btn-group btn-group-sm">
                    {% if object %}
                        <button type="submit" class="btn btn-primary">
                            <span class="glyphicon glyphicon-save"></span> {% trans 'Save' %}
                        </button>
                    {% else %}
                        <button type="submit" class="btn btn-success">
                            <span class="glyphicon glyphicon-plus"></span> {% trans 'Add' %}
                        </button>
                    {% endif %}
                    <button type="reset" class="btn btn-default">
                        <span class="glyphicon glyphicon-remove-circle"></span> {% trans 'Reset' %}
                    </button>
                    {% if object %}
                        <a href="{% url 'finapp:pay_history' object.slug %}" class="btn btn-default">
                            <span class="glyphicon glyphicon-list"></span> {% trans 'Payment history' %}
                        </a>
                    {% endif %}
                </div>
            </form>
        </div>
    </div>
{% endblock %}

finapp/templates/finapp/payalltimegateway_list.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans 'List of payment gateways' %}{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><span class="glyphicon glyphicon-home"></span></li>
        <li class="active">{% trans 'Payment system' %}</li>
    </ol>
{% endblock %}

{% block page-header %}
    {% trans 'List of payment gateways' %}
{% endblock %}


{% block main %}

    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th class="col-sm-7">{% trans 'Title' %}</th>
            <th class="col-sm-3">{% trans 'Service id' %}</th>
            <th class="col-sm-1">{% trans 'Pays count' %}</th>
            <th class="col-sm-1"></th>
        </tr>
        </thead>
        <tbody>
        {% for gw in object_list %}
            <tr>
                <td>{{ gw.title }}</td>
                <td>{{ gw.service_id }}</td>
                <td>{{ gw.pays_count }}</td>
                <td class="btn-group btn-group-sm">
                    {% if perms.finapp.change_payalltimegateway %}
                        <a href="{% url 'finapp:edit_pay_gw' gw.slug %}" class="btn btn-default" title="{% trans 'Edit' %}" data-toggle="tooltip">
                            <span class="glyphicon glyphicon-edit"></span>
                        </a>
                    {% else %}
                        <a href="#" class="btn btn-default" title="{% trans 'Permission required' %}" disabled data-toggle="tooltip">
                            <span class="glyphicon glyphicon-edit"></span>
                        </a>
                    {% endif %}
                    {% if perms.finapp.view_alltimepaylog %}
                        <a href="{% url 'finapp:pay_history' gw.slug %}" class="btn btn-default" title="{% trans 'Payment history' %}" data-toggle="tooltip">
                            <span class="glyphicon glyphicon-list"></span>
                        </a>
                    {% endif %}
                </td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="4">{% trans 'Payment gateways not found' %}</td>
            </tr>
        {% endfor %}
        </tbody>
        <tfoot>
        <tr>
            <td colspan="4" class="btn-group btn-group-sm">
                {% if perms.finapp.add_payalltimegateway %}
                    <a href="{% url 'finapp:add_alltime_gateway' %}" class="btn btn-default">
                        <span class="glyphicon glyphicon-plus"></span> {% trans 'Add' %}
                    </a>
                {% else %}
                    <a href="#" class="btn btn-default" title="{%  trans 'Permission required' %}" disabled>
                        <span class="glyphicon glyphicon-plus"></span> {% trans 'Add' %}
                    </a>
                {% endif %}
                {% if request.user.is_superuser %}
                    <a href="{% url 'finapp:fin_report' %}" class="btn btn-default">
                        <span class="glyphicon glyphicon-usd"></span> <span class="hidden-xs">{% trans 'Fin report' %}</span>
                    </a>
                {% endif %}
            </td>
        </tr>
        </tfoot>

    </table>

{% endblock %}